env:
  global:
      - REPO_DIR=Pillow
      - BUILD_COMMIT=HEAD
      - PLAT=x86_64
      - UNICODE_WIDTH=32

language: python
# Default Python version is usually 2.7
python: 3.5
dist: xenial
services: docker
osx_image: xcode9.4

matrix:
  exclude:
      # Exclude the default Python 3.5 build
      - python: 3.5
  include:
    - name: "3.7 macOS"
      os: osx
      language: generic
      env:
        - MB_PYTHON_VERSION=3.7

before_install:
    - source multibuild/common_utils.sh
    - source multibuild/travis_steps.sh
    - before_install

script:
    - pip install py2app Pillow
    - cd pillow_mac_setup && python setup.py py2app