
name: Wheels

on: [push, pull_request]

jobs:
  build:
    name: "Test"
    runs-on: "ubuntu-16.04"
    steps:
      - name: Test
        run: |
          wget https://downloads.python.org/pypy/pypy3.7-v7.3.3-linux32.tar.bz2
          tar -xf pypy3.7-v7.3.3-linux32.tar.bz2
          pypy3.7-v7.3.3-linux32/bin/pypy3 -m ensurepip
          pypy3.7-v7.3.3-linux32/bin/pypy3 -m pip install numpy