
name: Wheels

on: [push, pull_request]

env:
  REPO_DIR: Pillow
  BUILD_DEPENDS: ""
  TEST_DEPENDS: "pytest pytest-cov"
  WHEEL_SDIR: wheelhouse

jobs:
  build:
    name: ${{ matrix.python }} ${{ matrix.os-name }} ${{ matrix.platform }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ "ubuntu-16.04", "macos-latest" ]
        python: [ "3.8", "3.9" ]
        platform: [ "x86_64", "i686" ]
        macos-target: [ "10.10" ]
        exclude:
          - os: "ubuntu-16.04"
            platform: "i686"
          - os: "ubuntu-16.04"
            platform: "x86_64"
          - os: "macos-latest"
            platform: "i686"
        include:
          - os: "macos-11.0"
            os-name: "osx"
            platform: "arm64"
            python: "3.9"
            macos-target: "11.0"
    env:
      BUILD_COMMIT: HEAD
      PLAT: ${{ matrix.platform }}
      MB_PYTHON_VERSION: ${{ matrix.python }}
      TRAVIS_OS_NAME: ${{ matrix.os-name }}
      MACOSX_DEPLOYMENT_TARGET: ${{ matrix.macos-target }}
    steps:
      - name: Build Wheel
        run: |
          ls /Applications | grep Xcode
          echo "Before"
          xcode-select -p || true
          sudo xcode-select -switch /Applications/Xcode_11.7.app || true
          echo "Mid"
          xcode-select -p || true
          echo "mid_sdk"
          xcrun -show-sdk-version
          x=$(ls /Applications | grep Xcode[_0-9\.]*\.app | sort -V | tail -n 1)
          echo "x"
          echo $x
          sudo xcode-select -switch /Applications/$x || true
          echo "After"
          xcode-select -p || true
          echo "after_sdk"
          xcrun -show-sdk-version